PDF/mypdf/mypdf/urls.py
from base64 import urlsafe_b64decode
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pdfapp.urls', namespace='pdfapp')),
]

urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)

PDF/mypdf/pdfapp/urls.py
from django.urls import path
from .views import render_pdf_view,CustomerListView,customer_render_pdf_view


app_name='pdfapp'

urlpatterns=[
    path('',CustomerListView.as_view(), name='customer-list-view'),
    path('test/',render_pdf_view, name='test-view'),
    path('pdf/<pk>',customer_render_pdf_view, name='customer-pdf-view'),
    
]

PDF/mypdf/pdfapp/models.py
from django.db import models

# Create your models here.
class Customer(models.Model):
    name = models.CharField(max_length=200)
    logo = models.ImageField()
    description = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.name)

PDF/mypdf/pdfapp/views.py
from cmath import pi
from msilib.schema import ListView
from urllib import response
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa
from django.views.generic import ListView
from .models import Customer


# Create your views here.
class CustomerListView(ListView):
    model = Customer
    template_name = 'customers/main.html'

def customer_render_pdf_view(request, *args, **kwargs):
    pk = kwargs.get('pk')
    customer = get_object_or_404(Customer,pk=pk)

    template_path = 'customers/pdf2.html'
    context={'customer':customer}

    #Create a django response object and specify content_type as pdf
    response = HttpResponse(content_type = 'application/pdf')
    # response['Content-Disposition'] = 'attachment; filename = "report.pdf"'
    
    #find the template and render it
    template = get_template(template_path)
    html = template.render(context)

    #create pdf
    pisa_status = pisa.CreatePDF(
        html, dest = response
    )

    #if error then show some funny view
    if pisa_status.err:
        return HttpResponse("we had some errors<pre>" + html + "<pre>")
    return response    






def render_pdf_view(request):
    template_path = 'customers/pdf1.html'
    context={'myvar':'this is my template path'}

    #Create a django response object and specify content_type as pdf
    response = HttpResponse(content_type = 'application/pdf')
    # response['Content-Disposition'] = 'attachment; filename = "report.pdf"'
    
    #find the template and render it
    template = get_template(template_path)
    html = template.render(context)

    #create pdf
    pisa_status = pisa.CreatePDF(
        html, dest = response
    )

    #if error then show some funny view
    if pisa_status.err:
        return HttpResponse("we had some errors<pre>" + html + "<pre>")
    return response    

PDF/mypdf/pdfapp/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>pdfs |{% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
        {% block content %}

        {% endblock content %}

    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </body>
</html>

PDF/mypdf/templates/customers/main.html
{% extends 'base.html' %}

{% block title %}

{% endblock title %}

{% block content %}

  {% for customer in object_list %}
    {{customer}}
    <a href="{% url 'pdfapp:customer-pdf-view' customer.pk %}"><button class="btn btn-primary">pdf</button></a>
    <br>
    <hr>
  
  {% endfor %}

{% endblock content %}

PDF/mypdf/templates/customers/pdf1.html
<html>
    <head>
        <meta charset="utf-8">
        <title>pdf test</title>
    </head>
    <body>
        {{myvar}}
    </body>
</html>

PDF/mypdf/templates/customers/pdf2.html
<html>
    <head>
        <meta charset="utf-8">
        <title>pdf test</title>
        <style>
            table,th,td{
                border:1px solid black;
            }
            .centre{
                text-align: center;

            }
            .image1{
                margin-left: 650px;
            }
            .image{
                margin-left: 300px;
            }
            .detail{
                margin-left: 100px;
            }
            .id{
                margin-left: 400px;
            }
            .off{
                margin-left: 70px;
            }
            
        </style>
    </head>
    <body>
        {% block content %}
        
        <div class="">
            <h1>IMAGE1</h1><h1 class="image1">IMAGE2</h1>
                <h1 class="centre">MOI UNIVERSITY 
                    <p>EXAMINATION CARD</p>
                    <p>2019/2020 ACADEMIC YEAR</p>
                </h1>
            
            <p></p>
            
            <div class="detail">
                <h2>Office of the Deputy Vice Chancellor (Academic Affairs)</h2>
                <p>AUTHORIZATION TO SIT UNIVERSITY EXAMINATION</p>
                <h1>TED/90/18</h1>
                <h1>MWATSUKIZI SWALEH</h1>
                <p>Bachelor of Education (Technology Education And Computer)</p>
                <p>STAGE: Y4S1 SEMESTER: SEM1 21/22</p>
            </div>
            <p class="id">##73865**</p>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">CODE</th>
                        <th scope="col">DESCRIPTION</th>
                        <th scope="col">BOOKLET NO</th>
                        <th scope="col">LECTURER SIGNATURE</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th scope="row">
                            <P>BCT 411E</P>
                            <P>BCT 421E</P>
                            <P>BCT 431E</P>
                           <P>EDU 499</P>
                           <P>EMP 410</P>
                           <P>EMP 411</P>
                           <P>TEC 400</P>
                           <P>TEC 401</P>
                           <P>TEC 490</P>
                        </th>
                        <td>
                            <P>Architectural Drawing</P>
                            <p>Structures II</p>
                            <P>Quantity Survey II</P>
                            <p>Research Project</p>
                            <p>Environmental Education</p>
                            <p>Educational Administration & Management</p>
                            <p>Technology Trip II(Week 1)</p>
                            <p>Micro Processing System</p>
                            <p>Project (Final Year)</p>

                        </td>
                       
                    </tr>
                    
                </tbody>
                

            </table>
        
            <div class="off">
            <h1>Official Signature $ Stamp:</h1>
            <p><h1>73865</h1></p>
            </div>
            
            <div class="image">
                <img src="{{customer.logo.path}}" height="200px"/>
    
            </div>
            


        </div>
        {% endblock %}


       





       
         
    </body>
</html>